/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pvzgame;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author c.chuchmach
 */
public class GameOver extends javax.swing.JFrame {

    /**
     * Creates new form gameover
     */
    public GameOver() {
        initComponents();
        setSize(534, 443);
        setLocationRelativeTo(null);
        this.setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        menuBtn2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/gameover.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 530, 420);

        menuBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/mainMenuBtn.png"))); // NOI18N
        menuBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtn2MouseClicked(evt);
            }
        });
        getContentPane().add(menuBtn2);
        menuBtn2.setBounds(240, 360, 80, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtn2MouseClicked

        this.dispose();
        try {
            StartScreen menu = new StartScreen();
        } catch (IOException ex) {
            Logger.getLogger(GameOver.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuBtn2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel menuBtn;
    private javax.swing.JLabel menuBtn1;
    private javax.swing.JLabel menuBtn2;
    // End of variables declaration//GEN-END:variables
}
